project: default
source:
  repoURL: 'https://github.com/thirst-alert/thirst-alert-iac.git'
  path: ./modules/gke/argocd/be
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - Replace=true