apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: ta-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/thirst-alert/thirst-alert-be/backend:v1.2.0-dev.5
        name: backend
        resources: {}
        env:
        - name: NODE_ENV
          value: "dev"
        - name: ERR_VERBOSE
          value: "true" # set to false in production
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: MONGO_URI
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: ta-backend
spec:
  rules:
  - host: api.thirst-alert.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000