apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: ta-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/thirst-alert/thirst-alert-be/backend:v1.2.0-dev.4
        name: backend
        resources: {}
        env:
        - name: NODE_ENV
          value: "dev"
        - name: ERR_VERBOSE
          value: "true" # set to false in production
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: be-secrets
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort:  30000